export const FETCH_ALL_DATA_REQUEST = "FETCH_ALL_DATA_REQUEST"
export const FETCH_ALL_DATA_SUCCESS = "FETCH_ALL_DATA_SUCCESS"
export const FETCH_ALL_DATA_ERROR = "FETCH_ALL_DATA_ERROR"

export const FETCH_RANDOM_POKEMON_DATA_REQUEST = "FETCH_RANDOM_POKEMON_DATA_REQUEST"
export const FETCH_RANDOM_POKEMON_DATA_SUCCESS = "FETCH_RANDOM_POKEMON_DATA_SUCCESS"
export const FETCH_RANDOM_POKEMON_DATA_ERROR = "FETCH_RANDOM_POKEMON_DATA_ERROR"